project:
  type: book

book:
  title: "Statistics Portfolio"
  author: "Valdinar Pires"
  date: "2026"
  chapters:
  - index.qmd
  - intro.qmd
  - summary.qmd
  - references.qmd

bibliography: references.bib

format:
  html:
    number-sections: false
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt 